from requests import Session
from requests.auth import HTTPBasicAuth
from lxml import etree
from urllib.request import Request, urlopen
import urllib
import urllib.parse
import ssl
import base64
import warnings
import requests
import xml.etree.ElementTree as ET

warnings.simplefilter("ignore")

class CMS:
    def __init__(self, host: str, username: str, password: str):
        self.host = host
        session = Session()
        session.verify = False
        session.auth = HTTPBasicAuth(username, password)
        self.session = session
        self.headers = {"Content-Type": "application/x-www-form-urlencoded"}

        self.BASE_URL = self.host+"api/v1/" ### never changes קבוע
        requests.packages.urllib3.disable_warnings() ### canceled the ssl alert 
        
    ###########general functions################
    #### for a general get functions
    def cms_get(self,endpoint):
        return requests.get(f"{self.BASE_URL}/{endpoint}",
        auth=self.session.auth,verify=False)
    
    ### for a general put functions
    def cms_put(self,endpoint, data):
        return requests.put(f"{self.BASE_URL}/{endpoint}",
        data=data,auth=self.session.auth,verify=False)
    
    
    #### for a general post functions // adding new objects
    def cms_post(self,endpoint,data=None):
        #print(self.headers)
        return requests.post(f"{self.BASE_URL}/{endpoint}",
        data=data,auth=self.session.auth,verify=False)
    
    ### for a general delete functions
    def cms_delete(self,endpoint,data=None):
        return requests.delete(f"{self.BASE_URL}/{endpoint}",
        data=data,auth=self.session.auth,verify=False)
    
    ###############################################

      
     
    ###get cospace_details by cosapce_uuid
    def get_cospace_details(self,cospace_id):
        response = self.cms_get(f"coSpaces/{cospace_id}")
        if response.status_code== 200:
            root = ET.fromstring(response.text)
            details = {
                "name": root.findtext("name"),
                "uri":  root.findtext("uri"),
                "passcode": root.findtext("passcode"),
                "secondaryUri": root.findtext("secondaryUri")
            }
            return details
        else:
            print(f"Error: {response.status_code}")
            return None        
    

    def etree_to_dict(self,tree):
        # print(tree)
        d = {}
        if tree.tag is None:
            return tree.text
        if tree.attrib:
            if 'total' in tree.attrib:
                d['total meetings'] = tree.attrib
            if 'id' in tree.attrib:
                d['attributes'] = tree.attrib
        children = tree.getchildren()
        if children:
            # print(children)
            for child in children:
                # print(child.tag)
                child_dict = self.etree_to_dict(child)
                if child.tag in d:
                    # print(child.tag)
                    if type(d[child.tag]) == list:
                        d[child.tag].append(child_dict)
                    else:
                        d[child.tag] = [d[child.tag],child_dict]
                else:
                    d[child.tag] = child_dict
        else:
            d[tree.tag] = tree.text
        return d

    def xml_to_dict_all_meetings(self, xml_string):#TODO: need to do more tests
        root = etree.fromstring(xml_string)
        all_data = self.etree_to_dict(root)
        # print(all_data)
        output_dict = []
        try:
            output_dict.append({'total meetings':all_data['total meetings']['total']})
        except Exception as e:
            print(e)
        try:
            for data in all_data['coSpace']:
                temp = {}
                # print(type(data))
                if type(data) == dict: # when there is more than 1 meeting
                    try:
                        temp['unique id'] = data['attributes']['id']
                    except:
                        temp['unique id'] = ""
                    try:
                        temp['name'] = data['name']['name']
                    except:
                        temp['name'] = ""
                    try:
                        temp['uri'] = data['uri']['uri']
                    except:
                        temp['uri'] = ""
                    try:
                        temp['callId'] = data['callId']['callId']
                    except:
                        temp['callId'] = ""
                    try:
                        temp['autoGenerated'] = data['autoGenerated']['autoGenerated']        
                    except:
                        temp['autoGenerated'] = ""
                    output_dict.append(temp)
                if type(data) == str:
                    try:
                        temp['unique id'] = all_data['coSpace']['attributes']['id']
                        # output_dict.append(all_data['coSpace']['attributes'])
                    except:
                        temp['unique id'] = ""
                    try:
                        temp['name'] = all_data['coSpace']['name']['name']
                        # output_dict.append(all_data['coSpace']['name'])
                    except:
                        temp['name'] = ""
                    try:
                        temp['uri'] = all_data['coSpace']['uri']['uri']
                        # output_dict.append(all_data['coSpace']['uri'])
                    except:
                        temp['uri'] = ""
                    try:
                        temp['callId'] = all_data['coSpace']['callId']['callId']
                        # output_dict.append(all_data['coSpace']['callId'])
                    except:
                        temp['callId'] = ""
                    try:
                        temp['autoGenerated'] = all_data['coSpace']['autoGenerated']['autoGenerated']
                        # output_dict.append(all_data['coSpace']['autoGenerated'])
                    except:
                        temp['autoGenerated'] = ""

                    output_dict.append(temp)
                    return output_dict
        except:
            print("no meetings found")
            output_dict = [{'message':"no meetings found"}]
        return output_dict
    
    def get_meeting_details(self, meeting_id):
        url = self.host+"api/v1/coSpaces/"+meeting_id
        headers = {"Content-Type": "application/x-www-form-urlencoded"}
        output = self.session.get(url=url, headers=headers).text
        dict_output = self.xml_to_dict_specific_meeting(output)

        return dict_output
    
    def get_all_cospace_details(self):
        # print(1)
        response = self.cms_get(f"coSpaces")
        dict_output = self.xml_to_dict_all_meetings(response.text)

        # finding the remaining meetings
        total_meetings = int(dict_output[0]['total meetings'])
        # print(total_meetings)
        added_meetings = len(dict_output)-1
        # print(added_meetings)

        all_meetings = []
        if total_meetings > added_meetings:
            while total_meetings > added_meetings:
                # print(1)
                url = "coSpaces?filter="+"&offset="+str(added_meetings)+"&limit=20"
                # print(url)
                output_temp = self.cms_get(url).text
                # print(output_temp)
                dict_output_temp = self.xml_to_dict_all_meetings(output_temp)
                for element in dict_output_temp:
                    if 'total meetings' not in element:
                        all_meetings.append(element)
                added_meetings += 20
        
        # print(all_meetings)
        # getting the additional details
        save_data = []
        for meeting in all_meetings:
            if 'total meetings' not in meeting:
                print(meeting)
                meeting_uuid = meeting['unique id']
                full_meeting = self.get_cospace_details(meeting_uuid)
                meeting_passcode = full_meeting['passcode']
                save_data.append({
                    'Meetings':meeting['uri'],
                    'Password':meeting_passcode,
                    'Name':meeting['name']
                })
        return save_data        


    ### update the cospace passcode
    def update_cospace_passcode(self,cospace_id, new_passcode):
        data = {"passcode": new_passcode}
        response = self.cms_put(f"coSpaces/{cospace_id}",data=data)
        if response.status_code == 200:
             return  True
        else:
            return False
        
    
    ### get the cospace id by the meeting number
    def find_cospace_id_by_uri(self,uri_search):
        response = self.cms_get(f"coSpaces?filter={uri_search}")
        if response.status_code== 200:
            root = ET.fromstring(response.text)
            cospace = root.find("coSpace")
            if cospace is not None:
                return cospace.get("id")
        else:
            print(f"Error: {response.status_code}")
            return None  
    
    ### return all the calls_ids of all active calls on the server
    def get_all_active_calls_ids(self):
        response = self.cms_get(f"calls")
        if response.status_code== 200:
            root = ET.fromstring(response.text)
            active_calls=[]
            for call in root.findall('call'):
                active_calls.append(call.get('id'))
            return active_calls    
        else:
            print(f"Error: {response.status_code}")
            return None  
    
    ### return all the active calls details
    def get_active_calls_with_details(self):
        calls_ids = self.get_all_active_calls_ids()
        call_details = []
        
        for c_id in calls_ids:
            response = self.cms_get(f"calls/{c_id}")
            if response.status_code == 200:
                root = ET.fromstring(response.text)
                legs_resp = self.cms_get(f"calls/{c_id}/callLegs") ### כמות משתתפים על הוועידה
                num_participants = 0
                if legs_resp.status_code == 200:
                    legs_root = ET.fromstring(legs_resp.text)
                    num_participants = len(legs_root.findall('callLeg'))
            
            call_details.append({
                "call_id": c_id,
                "name":root.findtext("name"),
                "participants": num_participants
            })
        return call_details    
    
    ### creating a new coSpace and returnes the new cospace_id ** most be checked
    def create_cospace(self,room_name,room_uri,password=None):
        if password: 
            data2={"name":str(room_name) ,"uri":str(room_uri),"callId":str(room_uri),"passcode":str(password)}
        else:
            data2={"name":str(room_name) ,"uri":str(room_uri),"callId":str(room_uri)}
        response = self.cms_post(f"coSpaces",data=data2)
        if response.status_code == 200 or response.status_code == 201: #### means created
            return True
        else:
            print(f"Failed to create coSpace: {response.status_code}")
            return False

    ### need to check before use that u put the call id and not the cosapce id
    def kick_participants(self,call_id,participant_name):
        response = self.cms_get(f"calls/{call_id}/callLegs")
        if response.status_code == 200:
            print(response.text)
            root = ET.fromstring(response.text)
            for leg in root.findall('callLeg'):
                leg_id = leg.get('id')
                leg_detail = self.cms_get(f"callLegs/{leg_id}")
                leg_root = ET.fromstring(leg_detail.text)
                current_name = leg_root.findtext("remoteParty")
                print(current_name)
                if participant_name in str(current_name):
                    del_resp=self.cms_delete(f"callLegs/{leg_id}")
                    if del_resp.status_code == 200:
                        print("kicked")
                        return True
            print("not found")            
            return False
                    
    def get_cms_status(self):
        response = self.cms_get(f"system/status")
        if response.status_code == 200:
            root = ET.fromstring(response.text)
            status = {
                "TOTAL PARTICIPANTS": root.findtext(".//{*}callLegsActive")
                #"audioCalls": root.findtext(".//{*}audioCalls"),
                #"videoCalls": root.findtext(".//{*}videoCalls"),
                #"cpuLoad": root.findtext(".//{*}cpuLoad")
            }
            return status
        return None
    
    def get_call_participants(self,call_id):
        response = self.cms_get(f"calls/{str(call_id)}")
        print(response)
        if response.status_code == 200:
            root = ET.fromstring(response.text)
            legs = root.findtext("numParticipantsLocal")
            print(legs)
        else:
            print("error")

    ### שינוי LAYOUT למשתתף ספציפי
    def set_participant_layout(leg_id,layout_type="allEqual"):
        payload = {"layout":layout_type}
        response = self.cms_put(f"callLegs/{leg_id}",data=payload)
        
        if response.status_code == 200:
            printf("layout for this participant changed")
            return True
        print("layout did not changed")    
        return False    
    
    ### delete a cospace
    def delete_cospace(self,cospace_id):
        response = self.cms_delete(f"coSpaces/{cospace_id}")
        if response.status_code == 200:
            printf("coSpace deleted")
            return True
        print("coSpace not deleted")    
        return False

    ### getting the call_id by the cospace_id
    def get_active_call_id_by_cospace_id(self,cospace_id):
        response = self.cms_get(f"calls")
        root = ET.fromstring(response.text)
        for call in root.findall("call"):
            call_id = call.get('id')

            call_detail = self.cms_get(f"calls/{call_id}")
            if call_detail.status_code == 200:
                call_root = ET.fromstring(call_detail.text)
                if call_root.findtext("coSpace") == cospace_id:
                    return call_id
        return None                

     
    #### returns the leg_id of a specific participants who was found on a call
    def get_participant_leg_id(self,call_id,participant_name):
        response = self.cms_get(f"calls/{call_id}/callLegs")
        if response.status_code == 200:
            root = ET.fromstring(response.text)
            legs = root.findall("callLeg")
            for leg in legs:
                leg_id = leg.get('id')
                #print(leg_id)
                leg_detail = self.cms_get(f"callLegs/{leg_id}")
                if leg_detail.status_code == 200:
                    leg_root= ET.fromstring(leg_detail.text)
                    name_in_cms = leg_root.findtext("remoteParty")
                    #print(name_in_cms)
                    if name_in_cms and participant_name.lower() in name_in_cms.lower():
                        return leg_id
    

    ## if you put true it will mute the user and false for unmute the user
    def mute_participant(self,leg_id,mute_state=True):
        payload = {"rxAudioMute":"true" if mute_state else "false"}
        response = self.cms_put(f"callLegs/{leg_id}",data=payload)
        if response.status_code == 200:
            status = "Muted" if mute_state else "Unmuted"
            print(f"Participant {leg_id} is now {status}")
            return True
        return False    
    
    ### basic function to kick participant
    def kick_participant(self,leg_id):
        response = self.cms_delete(f"callLegs/{leg_id}")
        if response.status_code == 200:
            print(f"Participant {leg_id} was kicked from the call")
            return True
        return False

    ### change the name of a cospace
    def rename_cospace(self,cosapce_id,new_name):
        payload = {"name":str(new_name)}
        response = self.cms_put(f"coSpace/{cospace_id}",data=payload)
        if response.status_code == 200:
            print("name changed")
            return True
        return False    