"""Initial CENSUS migration

Revision ID: 8f8286251bea
Revises: 
Create Date: 2026-03-26 04:19:40.497114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f8286251bea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create users table
    op.create_table('users',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('sam_account_name', sa.String(length=100), nullable=False),
        sa.Column('distinguished_name', sa.Text(), nullable=True),
        sa.Column('object_guid', sa.String(length=36), nullable=True),
        sa.Column('display_name', sa.String(length=200), nullable=True),
        sa.Column('first_name', sa.String(length=100), nullable=True),
        sa.Column('last_name', sa.String(length=100), nullable=True),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('department', sa.String(length=100), nullable=True),
        sa.Column('title', sa.String(length=100), nullable=True),
        sa.Column('office', sa.String(length=100), nullable=True),
        sa.Column('manager', sa.String(length=200), nullable=True),
        sa.Column('employee_id', sa.String(length=50), nullable=True),
        sa.Column('phone_number', sa.String(length=50), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('last_ad_sync', sa.DateTime(timezone=True), nullable=True),
        sa.Column('raw_ad_attributes', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('sam_account_name'),
        sa.UniqueConstraint('object_guid')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    
    # Create devices table
    op.create_table('devices',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('device_type', sa.String(length=50), nullable=True),
        sa.Column('model', sa.String(length=100), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('mac_address', sa.String(length=17), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('owner_user_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('cucm_cluster', sa.String(length=100), nullable=True),
        sa.Column('last_seen_from_cucm', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_seen_from_scraper', sa.DateTime(timezone=True), nullable=True),
        sa.Column('raw_cucm_data', sa.JSON(), nullable=True),
        sa.Column('raw_scraper_data', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_index('ix_devices_status_cluster', 'devices', ['status', 'cucm_cluster'], unique=False)
    op.create_index(op.f('ix_devices_ip_address'), 'devices', ['ip_address'], unique=False)
    op.create_index(op.f('ix_devices_mac_address'), 'devices', ['mac_address'], unique=False)
    
    # Create lines table
    op.create_table('lines',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('directory_number', sa.String(length=50), nullable=False),
        sa.Column('partition', sa.String(length=100), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('usage_profile', sa.String(length=50), nullable=True),
        sa.Column('cucm_cluster', sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('directory_number', 'partition', 'cucm_cluster', name='uq_line_dn_partition_cluster')
    )
    op.create_index(op.f('ix_lines_directory_number'), 'lines', ['directory_number'], unique=False)
    
    # Create device_line_associations table
    op.create_table('device_line_associations',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('device_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('line_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('line_index', sa.Integer(), nullable=True),
        sa.Column('is_primary', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
        sa.ForeignKeyConstraint(['line_id'], ['lines.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('device_id', 'line_id', name='uq_device_line')
    )
    
    # Create switch_connections table
    op.create_table('switch_connections',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('device_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('switch_name', sa.String(length=100), nullable=True),
        sa.Column('switch_ip', sa.String(length=45), nullable=True),
        sa.Column('switch_model', sa.String(length=100), nullable=True),
        sa.Column('local_port', sa.String(length=50), nullable=True),
        sa.Column('remote_port', sa.String(length=50), nullable=True),
        sa.Column('port_description', sa.Text(), nullable=True),
        sa.Column('vlan', sa.String(length=50), nullable=True),
        sa.Column('discovery_protocol', sa.String(length=10), nullable=True),
        sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('raw_scrape_data', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_switch_conn_device', 'switch_connections', ['device_id', 'switch_name'], unique=False)
    
    # Create sync_logs table
    op.create_table('sync_logs',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('sync_type', sa.String(length=50), nullable=False),
        sa.Column('source', sa.String(length=100), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('records_processed', sa.Integer(), nullable=True),
        sa.Column('records_created', sa.Integer(), nullable=True),
        sa.Column('records_updated', sa.Integer(), nullable=True),
        sa.Column('records_failed', sa.Integer(), nullable=True),
        sa.Column('records_orphaned', sa.Integer(), nullable=True),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('duration_seconds', sa.Float(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('details', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_logs')
    op.drop_index('ix_switch_conn_device', table_name='switch_connections')
    op.drop_table('switch_connections')
    op.drop_table('device_line_associations')
    op.drop_index(op.f('ix_lines_directory_number'), table_name='lines')
    op.drop_table('lines')
    op.drop_index('ix_devices_status_cluster', table_name='devices')
    op.drop_index(op.f('ix_devices_mac_address'), table_name='devices')
    op.drop_index(op.f('ix_devices_ip_address'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
