
services:
  db:
    image: postgres:15
    container_name: cucm_db
    restart: always
    env_file:
      - ./backend/.env
    environment:
      - TZ=Asia/Jerusalem
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: ./backend
    container_name: cucm_app
    restart: always
    # מריץ את האפליקציה על פורט 8000 בתוך הקונטיינר
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8080:8000" # אתה תיכנס דרך http://localhost:8080
    env_file:
      - ./backend/.env
    environment:
      - TZ=Asia/Jerusalem
      - LOG_TIMEZONE=Asia/Jerusalem
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: