"""add group id to site

Revision ID: 72da985a76df
Revises: 43f25e43ac81
Create Date: 2026-04-12 23:35:10.575812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72da985a76df'
down_revision: Union[str, None] = '43f25e43ac81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('group_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'sites', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sites', type_='foreignkey')
    op.drop_column('sites', 'group_id')
    # ### end Alembic commands ###
