"""add user_id to sections

Revision ID: e3f8a9b2c4d5
Revises: d015ea6f3030
Create Date: 2026-04-30 14:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3f8a9b2c4d5'
down_revision: Union[str, None] = 'd015ea6f3030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'sections', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sections', type_='foreignkey')
    op.drop_column('sections', 'user_id')
    # ### end Alembic commands ###
